// Generated by scripts/sync-commercial-terms.mjs. Do not edit by hand.
export const HLD_COMMERCIAL_TERMS = {
  "schemaVersion": 1,
  "contractVersion": "2026-08-12-commercial-terms-v1",
  "effectiveAt": "2026-08-07T00:00:00Z",
  "currency": "usd",
  "membership": {
    "monthlyPriceCents": 1499,
    "billingInterval": "month",
    "billingIntervalCount": 1,
    "checkoutTermsVersion": "2026-08-07-membership-v2"
  },
  "paymentSetup": {
    "termsVersion": "2026-08-08-payment-setup-v1"
  },
  "offer": {
    "foundingOfferCode": "founding_two_months_90_day_v1",
    "outreachOfferCode": "outreach_two_months_90_day_v1",
    "freeBillingCycles": 2,
    "foundingInstructorLimit": 100,
    "invitationClaimDays": 14,
    "profileSubmissionDays": 7
  },
  "guarantee": {
    "termsVersion": "2026-08-07-90-day-paid-invoice-v1",
    "coverageDays": 90,
    "claimWindowDays": 30,
    "startEvent": "first_positive_paid_membership_invoice"
  },
  "billingRecovery": {
    "graceDays": 14,
    "eligibility": "at_least_one_positive_paid_membership_invoice"
  },
  "database": {
    "invitationPolicyMigration": "202608070001_instructor_invitation_claim_lifecycle.sql",
    "guaranteePolicyMigration": "202608070002_offer_billing_and_90_day_guarantee.sql",
    "paymentSetupPolicyMigration": "202608080001_pre_review_payment_setup.sql",
    "billingRecoveryPolicyMigration": "202608100003_fix_billing_recovery_notification_type.sql"
  }
} as const;

export const MONTHLY_PRICE_CENTS = HLD_COMMERCIAL_TERMS.membership.monthlyPriceCents;
export const INSTRUCTOR_FOUNDING_OFFER_CODE = HLD_COMMERCIAL_TERMS.offer.foundingOfferCode;
export const INSTRUCTOR_OUTREACH_OFFER_CODE = HLD_COMMERCIAL_TERMS.offer.outreachOfferCode;
export const INSTRUCTOR_OUTREACH_OFFER_MONTHS = HLD_COMMERCIAL_TERMS.offer.freeBillingCycles;
export const INSTRUCTOR_OFFER_FREE_PERIOD_LABEL = "two months";
export const INSTRUCTOR_OFFER_FREE_CYCLES_LABEL = "two free monthly billing cycles";
export const FOUNDING_INSTRUCTOR_LIMIT = HLD_COMMERCIAL_TERMS.offer.foundingInstructorLimit;
export const INVITATION_CLAIM_DAYS = HLD_COMMERCIAL_TERMS.offer.invitationClaimDays;
export const PROFILE_SUBMISSION_DAYS = HLD_COMMERCIAL_TERMS.offer.profileSubmissionDays;
export const MEMBERSHIP_CHECKOUT_TERMS_VERSION = HLD_COMMERCIAL_TERMS.membership.checkoutTermsVersion;
export const INSTRUCTOR_PAYMENT_SETUP_TERMS_VERSION = HLD_COMMERCIAL_TERMS.paymentSetup.termsVersion;
export const MEMBERSHIP_GUARANTEE_TERMS_VERSION = HLD_COMMERCIAL_TERMS.guarantee.termsVersion;
export const GUARANTEE_COVERAGE_DAYS = HLD_COMMERCIAL_TERMS.guarantee.coverageDays;
export const GUARANTEE_CLAIM_WINDOW_DAYS = HLD_COMMERCIAL_TERMS.guarantee.claimWindowDays;
export const BILLING_RECOVERY_GRACE_DAYS = HLD_COMMERCIAL_TERMS.billingRecovery.graceDays;
