-- Admin access, marketplace analytics, and instructor booking follow-ups.
-- Apply after 202608020011_payments_and_notification_workers.sql.

create table if not exists public.marketplace_admins (
  account_id uuid primary key references public.accounts(id) on delete cascade,
  is_owner boolean not null default false,
  granted_by uuid references public.accounts(id) on delete set null,
  granted_at timestamptz not null default now()
);

create table if not exists public.marketplace_admin_events (
  id bigint generated by default as identity primary key,
  actor_account_id uuid references public.accounts(id) on delete set null,
  target_account_id uuid references public.accounts(id) on delete set null,
  action text not null,
  created_at timestamptz not null default now(),
  constraint marketplace_admin_events_action_check check (action in ('granted', 'revoked'))
);

-- Preserve the current administrator as the permanent owner during the move
-- from a single account role to independently granted admin access.
insert into public.marketplace_admins (account_id, is_owner, granted_by)
select id, true, id
from public.accounts
where role = 'admin'
on conflict (account_id) do update set is_owner = true;

create or replace function public.is_marketplace_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.accounts account
    where account.id = auth.uid()
      and (
        account.role = 'admin'
        or exists (
          select 1
          from public.marketplace_admins admin_access
          where admin_access.account_id = account.id
        )
      )
  );
$$;

create or replace function public.current_marketplace_admin_status()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_marketplace_admin();
$$;

create or replace function public.current_marketplace_owner_status()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.marketplace_admins admin_access
    where admin_access.account_id = auth.uid()
      and admin_access.is_owner
  );
$$;

create or replace function public.protect_account_authority()
returns trigger
language plpgsql
as $$
begin
  if auth.role() = 'authenticated' then
    if new.id is distinct from old.id or new.email is distinct from old.email then
      raise exception 'Account identity fields cannot be changed here';
    end if;
    if new.role is distinct from old.role
      and coalesce(current_setting('hire_line_dancers.allow_role_change', true), '') <> 'on' then
      raise exception 'Account type changes must use the onboarding workflow';
    end if;
  end if;
  return new;
end;
$$;

drop policy if exists "account owners can update" on public.accounts;
create policy "account owners can update" on public.accounts
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

alter table public.marketplace_admins enable row level security;
alter table public.marketplace_admin_events enable row level security;

drop policy if exists "admins read admin access" on public.marketplace_admins;
create policy "admins read admin access" on public.marketplace_admins
  for select to authenticated using (public.is_marketplace_admin());

drop policy if exists "admins read admin access events" on public.marketplace_admin_events;
create policy "admins read admin access events" on public.marketplace_admin_events
  for select to authenticated using (public.is_marketplace_admin());

create or replace function public.list_marketplace_admins()
returns table (
  account_id uuid,
  email text,
  full_name text,
  is_owner boolean,
  granted_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_marketplace_admin() then
    raise exception 'Administrator access required';
  end if;

  return query
  select
    access.account_id,
    account.email,
    account.full_name,
    access.is_owner,
    access.granted_at
  from public.marketplace_admins access
  join public.accounts account on account.id = access.account_id
  order by access.is_owner desc, lower(coalesce(account.full_name, account.email, ''));
end;
$$;

create or replace function public.grant_marketplace_admin(p_email text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.accounts;
begin
  if not public.current_marketplace_owner_status() then
    raise exception 'Marketplace owner access required';
  end if;
  if nullif(trim(p_email), '') is null then
    raise exception 'Email is required';
  end if;

  select * into target
  from public.accounts
  where lower(email) = lower(trim(p_email))
  limit 1;

  if target.id is null then
    raise exception 'That person must sign in to Hire Line Dancers once before you can grant admin access';
  end if;

  insert into public.marketplace_admins (account_id, is_owner, granted_by)
  values (target.id, false, auth.uid())
  on conflict (account_id) do nothing;

  if found then
    insert into public.marketplace_admin_events (actor_account_id, target_account_id, action)
    values (auth.uid(), target.id, 'granted');
  end if;

  return target.id;
end;
$$;

create or replace function public.revoke_marketplace_admin(p_account_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.marketplace_admins;
begin
  if not public.current_marketplace_owner_status() then
    raise exception 'Marketplace owner access required';
  end if;
  if p_account_id = auth.uid() then
    raise exception 'You cannot revoke your own admin access';
  end if;

  select * into target
  from public.marketplace_admins
  where account_id = p_account_id
  for update;

  if target.account_id is null then
    raise exception 'Admin access record not found';
  end if;
  if target.is_owner then
    raise exception 'The marketplace owner cannot be removed';
  end if;

  delete from public.marketplace_admins where account_id = p_account_id;
  insert into public.marketplace_admin_events (actor_account_id, target_account_id, action)
  values (auth.uid(), p_account_id, 'revoked');
end;
$$;

alter table public.inquiries
  add column if not exists completion_status text not null default 'unknown',
  add column if not exists completion_reported_at timestamptz,
  add column if not exists completion_reported_by uuid references public.accounts(id) on delete set null,
  add column if not exists completion_followup_count integer not null default 0,
  add column if not exists completion_last_asked_at timestamptz,
  add column if not exists completion_next_ask_at timestamptz;

alter table public.inquiries
  drop constraint if exists inquiries_completion_status_check;
alter table public.inquiries
  add constraint inquiries_completion_status_check
  check (completion_status in ('unknown', 'completed', 'did_not_happen'));

create table if not exists public.inquiry_followup_responses (
  id bigint generated by default as identity primary key,
  inquiry_id uuid not null references public.inquiries(id) on delete cascade,
  instructor_account_id uuid not null references public.accounts(id) on delete cascade,
  stage text not null,
  response text not null,
  confirmed_event_date date,
  private_comment text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (inquiry_id, instructor_account_id, stage),
  constraint inquiry_followup_responses_stage_check check (stage in ('booking', 'completion')),
  constraint inquiry_followup_responses_response_check check (
    (stage = 'booking' and response in ('booked', 'not_booked', 'still_deciding'))
    or (stage = 'completion' and response in ('completed', 'did_not_happen'))
  ),
  constraint inquiry_followup_responses_comment_check check (
    private_comment is null or char_length(private_comment) <= 2000
  )
);

drop trigger if exists set_inquiry_followup_responses_updated_at on public.inquiry_followup_responses;
create trigger set_inquiry_followup_responses_updated_at
  before update on public.inquiry_followup_responses
  for each row execute function public.set_updated_at();

alter table public.inquiry_followup_responses enable row level security;

drop policy if exists "instructors and admins read private follow-up responses" on public.inquiry_followup_responses;
create policy "instructors and admins read private follow-up responses" on public.inquiry_followup_responses
  for select to authenticated
  using (instructor_account_id = auth.uid() or public.is_marketplace_admin());

-- A form submission is an inquiry. Ask the instructor about its booking result
-- seven days after submission, regardless of the proposed event date.
create or replace function public.set_inquiry_booking_followup_due_at()
returns trigger
language plpgsql
as $$
begin
  new.outcome_next_ask_at := coalesce(new.created_at, now()) + interval '7 days';
  return new;
end;
$$;

drop trigger if exists set_inquiry_booking_followup_due_at on public.inquiries;
create trigger set_inquiry_booking_followup_due_at
  before insert on public.inquiries
  for each row execute function public.set_inquiry_booking_followup_due_at();

-- Do not schedule retrospective emails for old test or historical inquiries.
-- Existing inquiries keep their records, while new inquiries use the corrected schedule.
update public.inquiries
set outcome_next_ask_at = null
where booking_outcome = 'unknown'
  and outcome_reported_at is null
  and created_at < timestamptz '2026-08-04 17:40:00+00';

create or replace function public.sync_inquiry_completion_schedule()
returns trigger
language plpgsql
as $$
declare
  resolved_event_date date;
  resolved_time_zone text;
begin
  if new.booking_outcome = 'booked' and new.completion_status = 'unknown' then
    resolved_event_date := coalesce(new.booking_event_date, new.event_date);
    new.booking_event_date := resolved_event_date;
    if resolved_event_date is not null then
      select timezone.name into resolved_time_zone
      from pg_catalog.pg_timezone_names timezone
      where timezone.name = new.time_zone
      limit 1;
      resolved_time_zone := coalesce(resolved_time_zone, 'America/New_York');
      new.completion_next_ask_at :=
        ((resolved_event_date + 2 + time '10:00') at time zone resolved_time_zone);
    end if;
  elsif new.booking_outcome <> 'booked' then
    new.completion_next_ask_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists sync_inquiry_completion_schedule on public.inquiries;
create trigger sync_inquiry_completion_schedule
  before insert or update of booking_outcome, booking_event_date, event_date, completion_status
  on public.inquiries
  for each row execute function public.sync_inquiry_completion_schedule();

create or replace function public.protect_completed_inquiry_outcome()
returns trigger
language plpgsql
as $$
begin
  if old.completion_status <> 'unknown'
    and (
      new.booking_outcome is distinct from old.booking_outcome
      or new.booking_event_date is distinct from old.booking_event_date
    ) then
    raise exception 'Booking details cannot be changed after event completion is recorded';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_completed_inquiry_outcome on public.inquiries;
create trigger protect_completed_inquiry_outcome
  before update of booking_outcome, booking_event_date on public.inquiries
  for each row execute function public.protect_completed_inquiry_outcome();

update public.inquiries
set completion_next_ask_at = null
where booking_outcome = 'booked'
  and completion_status = 'unknown'
  and created_at < timestamptz '2026-08-04 17:40:00+00';

-- Recalculate unsent completion reminders created after launch using the
-- instructor's event time zone and a daytime delivery hour.
update public.inquiries
set booking_event_date = booking_event_date
where booking_outcome = 'booked'
  and completion_status = 'unknown'
  and completion_next_ask_at is not null
  and created_at >= timestamptz '2026-08-04 17:40:00+00';

create index if not exists inquiries_created_at_idx
  on public.inquiries (created_at desc);
create index if not exists inquiries_outcome_followup_due_idx
  on public.inquiries (outcome_next_ask_at)
  where outcome_next_ask_at is not null;
create index if not exists inquiries_completion_followup_due_idx
  on public.inquiries (completion_next_ask_at)
  where completion_next_ask_at is not null;

create or replace function public.submit_instructor_inquiry_feedback(
  p_inquiry_id uuid,
  p_stage text,
  p_response text,
  p_private_comment text default null,
  p_confirmed_event_date date default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  inquiry public.inquiries;
  profile public.instructor_profiles;
  resolved_outcome text;
  resolved_event_date date;
  resolved_time_zone text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  if p_stage not in ('booking', 'completion') then
    raise exception 'Invalid feedback stage';
  end if;
  if char_length(coalesce(p_private_comment, '')) > 2000 then
    raise exception 'Comments must be 2,000 characters or fewer';
  end if;

  select * into inquiry
  from public.inquiries
  where id = p_inquiry_id
  for update;
  if inquiry.id is null then
    raise exception 'Inquiry not found';
  end if;

  select * into profile
  from public.instructor_profiles
  where id = inquiry.instructor_profile_id;
  if profile.id is null or profile.account_id <> auth.uid() then
    raise exception 'Only the contacted instructor can submit this feedback';
  end if;

  if p_stage = 'booking' then
    if inquiry.completion_status <> 'unknown' then
      raise exception 'Booking details cannot be changed after event completion is recorded';
    end if;
    if p_response not in ('booked', 'not_booked', 'still_deciding') then
      raise exception 'Choose Yes, No, or In progress';
    end if;
    resolved_event_date := coalesce(p_confirmed_event_date, inquiry.booking_event_date, inquiry.event_date);
    if p_response = 'booked' and resolved_event_date is null then
      raise exception 'Confirm the event date for this booking';
    end if;

    insert into public.inquiry_followup_responses (
      inquiry_id, instructor_account_id, stage, response,
      confirmed_event_date, private_comment
    ) values (
      inquiry.id, auth.uid(), 'booking', p_response,
      case when p_response = 'booked' then resolved_event_date end,
      nullif(trim(p_private_comment), '')
    )
    on conflict (inquiry_id, instructor_account_id, stage) do update set
      response = excluded.response,
      confirmed_event_date = excluded.confirmed_event_date,
      private_comment = excluded.private_comment,
      submitted_at = now(),
      updated_at = now();

    insert into public.inquiry_outcome_reports (
      inquiry_id, reporter_account_id, outcome, booking_value_cents, note
    ) values (
      inquiry.id, auth.uid(), p_response, null, null
    )
    on conflict (inquiry_id, reporter_account_id) do update set
      outcome = excluded.outcome,
      note = null,
      updated_at = now();

    select case
      when bool_or(outcome = 'booked') and bool_or(outcome = 'not_booked') then 'disputed'
      when bool_or(outcome = 'booked') then 'booked'
      when bool_or(outcome = 'not_booked') then 'not_booked'
      when bool_or(outcome = 'still_deciding') then 'still_deciding'
      else 'no_response'
    end
    into resolved_outcome
    from public.inquiry_outcome_reports
    where inquiry_id = inquiry.id;

    update public.inquiries set
      booking_outcome = resolved_outcome,
      booking_event_date = case
        when p_response = 'booked' then resolved_event_date
        else booking_event_date
      end,
      outcome_reported_by = auth.uid(),
      outcome_reported_at = now(),
      outcome_next_ask_at = null,
      status = case
        when resolved_outcome = 'booked' then 'booked'
        when resolved_outcome = 'not_booked' then 'not_booked'
        when status in ('booked', 'not_booked') and first_responded_at is not null then 'responded'
        when status in ('booked', 'not_booked') then 'submitted'
        else status
      end,
      closed_at = case
        when resolved_outcome in ('booked', 'not_booked') then now()
        else null
      end
    where id = inquiry.id;

    update public.inquiry_notification_jobs job
    set status = 'canceled', completed_at = now(), locked_at = null,
        last_error = 'Follow-up answered before delivery'
    from public.inquiry_recipients recipient
    where job.inquiry_recipient_id = recipient.id
      and recipient.inquiry_id = inquiry.id
      and job.notification_type = 'booking_followup'
      and job.status = 'pending';
  else
    if p_response not in ('completed', 'did_not_happen') then
      raise exception 'Choose Yes or No';
    end if;
    if inquiry.booking_outcome <> 'booked' then
      raise exception 'Record this inquiry as booked before reporting whether the event happened';
    end if;
    resolved_event_date := coalesce(inquiry.booking_event_date, inquiry.event_date);
    select timezone.name into resolved_time_zone
    from pg_catalog.pg_timezone_names timezone
    where timezone.name = inquiry.time_zone
    limit 1;
    resolved_time_zone := coalesce(resolved_time_zone, 'America/New_York');
    if resolved_event_date is not null
      and resolved_event_date > (now() at time zone resolved_time_zone)::date then
      raise exception 'The event date has not arrived yet';
    end if;

    insert into public.inquiry_followup_responses (
      inquiry_id, instructor_account_id, stage, response,
      confirmed_event_date, private_comment
    ) values (
      inquiry.id, auth.uid(), 'completion', p_response,
      resolved_event_date, nullif(trim(p_private_comment), '')
    )
    on conflict (inquiry_id, instructor_account_id, stage) do update set
      response = excluded.response,
      confirmed_event_date = excluded.confirmed_event_date,
      private_comment = excluded.private_comment,
      submitted_at = now(),
      updated_at = now();

    update public.inquiries set
      completion_status = p_response,
      completion_reported_at = now(),
      completion_reported_by = auth.uid(),
      completion_next_ask_at = null
    where id = inquiry.id;

    update public.inquiry_notification_jobs job
    set status = 'canceled', completed_at = now(), locked_at = null,
        last_error = 'Follow-up answered before delivery'
    from public.inquiry_recipients recipient
    where job.inquiry_recipient_id = recipient.id
      and recipient.inquiry_id = inquiry.id
      and job.notification_type = 'completion_followup'
      and job.status = 'pending';
  end if;
end;
$$;

alter table public.inquiry_notification_jobs
  drop constraint if exists inquiry_notification_status_check;
alter table public.inquiry_notification_jobs
  add constraint inquiry_notification_status_check
  check (status in ('pending', 'processing', 'sent', 'failed', 'canceled'));

create or replace function public.enqueue_due_inquiry_followups()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  booking_count integer := 0;
  completion_count integer := 0;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required';
  end if;

  update public.inquiry_notification_jobs job
  set status = 'canceled', completed_at = now(), locked_at = null,
      last_error = 'Follow-up is no longer needed'
  from public.inquiry_recipients recipient
  join public.inquiries inquiry on inquiry.id = recipient.inquiry_id
  where job.inquiry_recipient_id = recipient.id
    and job.status = 'pending'
    and (
      (job.notification_type = 'booking_followup' and exists (
        select 1 from public.inquiry_outcome_reports report
        join public.instructor_profiles profile on profile.account_id = report.reporter_account_id
        where report.inquiry_id = inquiry.id
          and profile.id = inquiry.instructor_profile_id
      ))
      or (
        job.notification_type = 'completion_followup'
        and (
          inquiry.booking_outcome <> 'booked'
          or inquiry.completion_status <> 'unknown'
          or inquiry.completion_next_ask_at is null
          or inquiry.completion_next_ask_at > now()
        )
      )
    );

  insert into public.inquiry_notification_jobs (
    inquiry_recipient_id, channel, notification_type, available_at
  )
  select recipient.id, 'email', 'booking_followup', now()
  from public.inquiries inquiry
  join public.inquiry_recipients recipient on recipient.inquiry_id = inquiry.id
  join public.instructor_profiles profile on profile.id = recipient.instructor_profile_id
  where inquiry.outcome_next_ask_at is not null
    and inquiry.outcome_next_ask_at <= now()
    and not exists (
      select 1
      from public.inquiry_outcome_reports report
      where report.inquiry_id = inquiry.id
        and report.reporter_account_id = profile.account_id
    )
  on conflict (inquiry_recipient_id, channel, notification_type) do update set
    status = 'pending',
    available_at = excluded.available_at,
    attempts = 0,
    locked_at = null,
    completed_at = null,
    last_error = null
  where public.inquiry_notification_jobs.status = 'canceled';
  get diagnostics booking_count = row_count;

  insert into public.inquiry_notification_jobs (
    inquiry_recipient_id, channel, notification_type, available_at
  )
  select recipient.id, 'email', 'completion_followup', now()
  from public.inquiries inquiry
  join public.inquiry_recipients recipient on recipient.inquiry_id = inquiry.id
  where recipient.instructor_profile_id is not null
    and inquiry.booking_outcome = 'booked'
    and inquiry.completion_status = 'unknown'
    and inquiry.completion_next_ask_at is not null
    and inquiry.completion_next_ask_at <= now()
  on conflict (inquiry_recipient_id, channel, notification_type) do update set
    status = 'pending',
    available_at = excluded.available_at,
    attempts = 0,
    locked_at = null,
    completed_at = null,
    last_error = null
  where public.inquiry_notification_jobs.status = 'canceled';
  get diagnostics completion_count = row_count;

  return booking_count + completion_count;
end;
$$;

create or replace function public.claim_inquiry_notification_jobs_v2(
  p_limit integer default 10,
  p_lock_timeout interval default interval '10 minutes'
)
returns table (
  job_id bigint,
  notification_type text,
  channel text,
  attempt_number integer,
  inquiry_recipient_id uuid,
  delivered_to_email text,
  delivered_to_phone_e164 text,
  inquiry_id uuid,
  instructor_name text,
  organizer_name text,
  organizer_email text,
  company_name text,
  event_type text,
  event_date date,
  event_start_time time,
  time_zone text,
  venue_name text,
  event_location text,
  guest_count integer,
  budget_range text,
  music_requests text,
  venue_has_speakers boolean,
  venue_has_microphone boolean,
  inquiry_message text
)
language sql
security definer
set search_path = public
as $$
  with exhausted as (
    update public.inquiry_notification_jobs job
    set status = 'failed',
        completed_at = now(),
        locked_at = null,
        last_error = coalesce(job.last_error, 'Worker stopped before the final attempt completed')
    where job.status = 'processing'
      and job.attempts >= 6
      and coalesce(job.locked_at, '-infinity'::timestamptz)
        < now() - greatest(p_lock_timeout, interval '1 minute')
    returning job.inquiry_recipient_id, job.channel, job.notification_type
  ), exhausted_recipients as (
    update public.inquiry_recipients recipient
    set email_delivery_status = case
          when exists (
            select 1 from exhausted
            where exhausted.inquiry_recipient_id = recipient.id
              and exhausted.channel = 'email'
              and exhausted.notification_type = 'new_inquiry'
          ) then 'failed'
          else recipient.email_delivery_status
        end,
        sms_delivery_status = case
          when exists (
            select 1 from exhausted
            where exhausted.inquiry_recipient_id = recipient.id
              and exhausted.channel = 'sms'
              and exhausted.notification_type = 'new_inquiry'
          ) then 'failed'
          else recipient.sms_delivery_status
        end,
        updated_at = now()
    where exists (
      select 1 from exhausted
      where exhausted.inquiry_recipient_id = recipient.id
        and exhausted.notification_type = 'new_inquiry'
    )
    returning recipient.id
  ), candidates as (
    select job.id
    from public.inquiry_notification_jobs job
    where job.attempts < 6
      and (
        (job.status = 'pending' and job.available_at <= now())
        or (
          job.status = 'processing'
          and coalesce(job.locked_at, '-infinity'::timestamptz)
            < now() - greatest(p_lock_timeout, interval '1 minute')
        )
      )
    order by job.available_at, job.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 10), 25))
  ), claimed as (
    update public.inquiry_notification_jobs job
    set status = 'processing',
        attempts = job.attempts + 1,
        locked_at = now(),
        last_error = null
    from candidates
    where job.id = candidates.id
    returning job.*
  )
  select
    claimed.id,
    claimed.notification_type,
    claimed.channel,
    claimed.attempts,
    recipient.id,
    case
      when claimed.notification_type = 'new_inquiry' then recipient.delivered_to_email
      else coalesce(settings.inquiry_email, recipient.delivered_to_email)
    end,
    case
      when claimed.notification_type = 'new_inquiry' then recipient.delivered_to_phone_e164
      else coalesce(settings.inquiry_phone_e164, recipient.delivered_to_phone_e164)
    end,
    inquiry.id,
    coalesce(profile.display_name, inquiry.instructor_name, 'Line dance instructor'),
    coalesce(inquiry.contact_name, inquiry.name),
    coalesce(inquiry.contact_email, inquiry.email),
    inquiry.company_name,
    inquiry.event_type,
    coalesce(inquiry.booking_event_date, inquiry.event_date),
    inquiry.event_start_time,
    inquiry.time_zone,
    inquiry.venue_name,
    coalesce(inquiry.location, concat_ws(', ', inquiry.event_city, inquiry.event_region)),
    inquiry.guest_count,
    inquiry.budget_range,
    inquiry.music_requests,
    inquiry.venue_has_speakers,
    inquiry.venue_has_microphone,
    inquiry.message
  from claimed
  join public.inquiry_recipients recipient on recipient.id = claimed.inquiry_recipient_id
  join public.inquiries inquiry on inquiry.id = recipient.inquiry_id
  left join public.instructor_profiles profile on profile.id = recipient.instructor_profile_id
  left join public.instructor_private_settings settings
    on settings.instructor_profile_id = recipient.instructor_profile_id;
$$;

create or replace function public.complete_inquiry_notification_job(
  p_job_id bigint,
  p_success boolean,
  p_provider_message_id text default null,
  p_error text default null,
  p_retryable boolean default false
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.inquiry_notification_jobs;
  next_status text;
  retry_seconds integer;
  related_inquiry_id uuid;
begin
  select * into job
  from public.inquiry_notification_jobs
  where id = p_job_id
  for update;

  if job.id is null then
    raise exception 'Notification job not found';
  end if;
  if job.status = 'sent' then
    return 'sent';
  end if;
  if job.status <> 'processing' then
    raise exception 'Notification job is not processing';
  end if;

  select inquiry_id into related_inquiry_id
  from public.inquiry_recipients
  where id = job.inquiry_recipient_id;

  if p_success then
    next_status := 'sent';
    update public.inquiry_notification_jobs
    set status = 'sent',
        provider_message_id = nullif(trim(p_provider_message_id), ''),
        sent_at = now(),
        completed_at = now(),
        locked_at = null,
        last_error = null
    where id = job.id;

    if job.notification_type = 'new_inquiry' then
      if job.channel = 'email' then
        update public.inquiry_recipients
        set email_delivery_status = 'sent',
            email_provider_message_id = nullif(trim(p_provider_message_id), ''),
            updated_at = now()
        where id = job.inquiry_recipient_id;
      else
        update public.inquiry_recipients
        set sms_delivery_status = 'sent',
            sms_provider_message_id = nullif(trim(p_provider_message_id), ''),
            updated_at = now()
        where id = job.inquiry_recipient_id;
      end if;
    elsif job.notification_type = 'booking_followup' then
      update public.inquiries
      set outcome_followup_count = outcome_followup_count + 1,
          outcome_last_asked_at = now(),
          outcome_next_ask_at = null
      where id = related_inquiry_id;
    elsif job.notification_type = 'completion_followup' then
      update public.inquiries
      set completion_followup_count = completion_followup_count + 1,
          completion_last_asked_at = now(),
          completion_next_ask_at = null
      where id = related_inquiry_id;
    end if;
  elsif p_retryable and job.attempts < 6 then
    next_status := 'pending';
    retry_seconds := least(1800, (30 * power(2, greatest(job.attempts - 1, 0)))::integer);

    update public.inquiry_notification_jobs
    set status = 'pending',
        available_at = now() + retry_seconds * interval '1 second',
        locked_at = null,
        last_error = left(coalesce(p_error, 'Provider request failed'), 2000)
    where id = job.id;

    if job.notification_type = 'new_inquiry' then
      if job.channel = 'email' then
        update public.inquiry_recipients
        set email_delivery_status = 'queued', updated_at = now()
        where id = job.inquiry_recipient_id;
      else
        update public.inquiry_recipients
        set sms_delivery_status = 'queued', updated_at = now()
        where id = job.inquiry_recipient_id;
      end if;
    end if;
  else
    next_status := 'failed';
    update public.inquiry_notification_jobs
    set status = 'failed',
        completed_at = now(),
        locked_at = null,
        last_error = left(coalesce(p_error, 'Provider request failed'), 2000)
    where id = job.id;

    if job.notification_type = 'new_inquiry' then
      if job.channel = 'email' then
        update public.inquiry_recipients
        set email_delivery_status = 'failed', updated_at = now()
        where id = job.inquiry_recipient_id;
      else
        update public.inquiry_recipients
        set sms_delivery_status = 'failed', updated_at = now()
        where id = job.inquiry_recipient_id;
      end if;
    end if;
  end if;

  return next_status;
end;
$$;

create or replace function public.defer_inquiry_notification_job(
  p_job_id bigint,
  p_error text,
  p_delay interval default interval '15 minutes'
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.inquiry_notification_jobs;
begin
  select * into job
  from public.inquiry_notification_jobs
  where id = p_job_id
  for update;

  if job.id is null then
    raise exception 'Notification job not found';
  end if;
  if job.status = 'sent' then
    return 'sent';
  end if;
  if job.status <> 'processing' then
    raise exception 'Notification job is not processing';
  end if;

  update public.inquiry_notification_jobs
  set status = 'pending',
      attempts = greatest(attempts - 1, 0),
      available_at = now() + greatest(p_delay, interval '1 minute'),
      locked_at = null,
      last_error = left(coalesce(p_error, 'Notification provider is not configured'), 2000)
  where id = job.id;

  if job.notification_type = 'new_inquiry' then
    if job.channel = 'email' then
      update public.inquiry_recipients
      set email_delivery_status = 'queued', updated_at = now()
      where id = job.inquiry_recipient_id;
    else
      update public.inquiry_recipients
      set sms_delivery_status = 'queued', updated_at = now()
      where id = job.inquiry_recipient_id;
    end if;
  end if;

  return 'pending';
end;
$$;

drop function if exists public.get_marketplace_admin_analytics(timestamptz, timestamptz, text);
create or replace function public.get_marketplace_admin_analytics(
  p_start timestamptz default null,
  p_end timestamptz default null,
  p_bucket text default 'day',
  p_time_zone text default 'America/New_York'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result jsonb;
  resolved_time_zone text;
begin
  if not public.is_marketplace_admin() then
    raise exception 'Administrator access required';
  end if;
  if p_start is not null and p_end is not null and p_start >= p_end then
    raise exception 'The start date must be before the end date';
  end if;
  if p_bucket not in ('day', 'week', 'month', 'year') then
    raise exception 'Invalid reporting interval';
  end if;

  select timezone.name into resolved_time_zone
  from pg_catalog.pg_timezone_names timezone
  where timezone.name = p_time_zone
  limit 1;
  resolved_time_zone := coalesce(resolved_time_zone, 'America/New_York');

  with filtered as (
    select inquiry.*
    from public.inquiries inquiry
    where (p_start is null or inquiry.created_at >= p_start)
      and (p_end is null or inquiry.created_at < p_end)
  ), outcome_activity as (
    select inquiry.*
    from public.inquiries inquiry
    where inquiry.outcome_reported_at is not null
      and (p_start is null or inquiry.outcome_reported_at >= p_start)
      and (p_end is null or inquiry.outcome_reported_at < p_end)
  ), completion_activity as (
    select inquiry.*, completion_event.occurred_at as completion_occurred_at
    from public.inquiries inquiry
    cross join lateral (
      select coalesce(
        (
          (coalesce(inquiry.booking_event_date, inquiry.event_date) + time '12:00')
          at time zone coalesce(
            (
              select timezone.name
              from pg_catalog.pg_timezone_names timezone
              where timezone.name = inquiry.time_zone
              limit 1
            ),
            resolved_time_zone
          )
        ),
        inquiry.completion_reported_at
      ) as occurred_at
    ) completion_event
    where inquiry.completion_status <> 'unknown'
      and completion_event.occurred_at is not null
      and (p_start is null or completion_event.occurred_at >= p_start)
      and (p_end is null or completion_event.occurred_at < p_end)
  ), summary as (
    select
      (select count(*)::integer from filtered) as inquiries,
      (select count(distinct coalesce(instructor_profile_id::text, instructor_slug))::integer from filtered) as instructors,
      (select count(distinct coalesce(
        'company:' || lower(nullif(trim(company_name), '')),
        'account:' || organizer_account_id::text
      ))::integer from filtered) as companies,
      (select count(*)::integer from outcome_activity where booking_outcome = 'booked') as booked,
      (select count(*)::integer from filtered where booking_outcome = 'still_deciding') as in_progress,
      (select count(*)::integer from outcome_activity where booking_outcome = 'not_booked') as not_booked,
      (select count(*)::integer from completion_activity where completion_status = 'completed') as completed,
      (select count(*)::integer from completion_activity where completion_status = 'did_not_happen') as did_not_happen,
      (select count(*)::integer from filtered where booking_outcome = 'booked') as cohort_booked,
      (select count(*)::integer from filtered where completion_status = 'completed') as cohort_completed
  ), instructor_rows as (
    select
      coalesce(filtered.instructor_profile_id::text, filtered.instructor_slug, 'unknown') as instructor_key,
      coalesce(profile.display_name, max(filtered.instructor_name), 'Unknown instructor') as instructor_name,
      count(*)::integer as inquiries,
      count(distinct coalesce(
        'company:' || lower(nullif(trim(filtered.company_name), '')),
        'account:' || filtered.organizer_account_id::text
      ))::integer as companies,
      count(*) filter (where filtered.booking_outcome = 'booked')::integer as booked,
      count(*) filter (where filtered.completion_status = 'completed')::integer as completed,
      max(filtered.created_at) as latest_inquiry_at
    from filtered
    left join public.instructor_profiles profile on profile.id = filtered.instructor_profile_id
    group by coalesce(filtered.instructor_profile_id::text, filtered.instructor_slug, 'unknown'), profile.display_name
  ), company_rows as (
    select
      coalesce(
        'company:' || lower(nullif(trim(filtered.company_name), '')),
        'account:' || filtered.organizer_account_id::text
      ) as company_key,
      coalesce(
        max(nullif(trim(filtered.company_name), '')),
        max(nullif(trim(filtered.contact_name), '')),
        'Individual organizer'
      ) as company_name,
      max(filtered.contact_email) as contact_email,
      count(*)::integer as inquiries,
      count(distinct coalesce(filtered.instructor_profile_id::text, filtered.instructor_slug))::integer as instructors,
      count(*) filter (where filtered.booking_outcome = 'booked')::integer as booked,
      count(*) filter (where filtered.completion_status = 'completed')::integer as completed,
      max(filtered.created_at) as latest_inquiry_at
    from filtered
    group by coalesce(
      'company:' || lower(nullif(trim(filtered.company_name), '')),
      'account:' || filtered.organizer_account_id::text
    )
  ), instructor_company_rows as (
    select
      coalesce(filtered.instructor_profile_id::text, filtered.instructor_slug, 'unknown') as instructor_key,
      coalesce(profile.display_name, max(filtered.instructor_name), 'Unknown instructor') as instructor_name,
      coalesce(
        'company:' || lower(nullif(trim(filtered.company_name), '')),
        'account:' || filtered.organizer_account_id::text
      ) as company_key,
      coalesce(
        max(nullif(trim(filtered.company_name), '')),
        max(nullif(trim(filtered.contact_name), '')),
        'Individual organizer'
      ) as company_name,
      max(filtered.contact_email) as contact_email,
      count(*)::integer as inquiries,
      count(*) filter (where filtered.booking_outcome = 'booked')::integer as booked,
      count(*) filter (where filtered.completion_status = 'completed')::integer as completed,
      max(filtered.created_at) as latest_inquiry_at
    from filtered
    left join public.instructor_profiles profile on profile.id = filtered.instructor_profile_id
    group by
      coalesce(filtered.instructor_profile_id::text, filtered.instructor_slug, 'unknown'),
      profile.display_name,
      coalesce(
        'company:' || lower(nullif(trim(filtered.company_name), '')),
        'account:' || filtered.organizer_account_id::text
      )
  ), activity_rows as (
    select created_at as occurred_at, 1 as inquiries, 0 as booked, 0 as completed
    from filtered
    union all
    select outcome_reported_at, 0, 1, 0
    from outcome_activity
    where booking_outcome = 'booked'
    union all
    select completion_occurred_at, 0, 0, 1
    from completion_activity
    where completion_status = 'completed'
  ), series_rows as (
    select
      date_trunc(p_bucket, activity_rows.occurred_at at time zone resolved_time_zone)::date as period_start,
      sum(activity_rows.inquiries)::integer as inquiries,
      sum(activity_rows.booked)::integer as booked,
      sum(activity_rows.completed)::integer as completed
    from activity_rows
    group by date_trunc(p_bucket, activity_rows.occurred_at at time zone resolved_time_zone)::date
  )
  select jsonb_build_object(
    'summary', coalesce((select to_jsonb(summary) from summary), '{}'::jsonb),
    'instructors', coalesce((
      select jsonb_agg(to_jsonb(instructor_rows) order by inquiries desc, instructor_name)
      from instructor_rows
    ), '[]'::jsonb),
    'companies', coalesce((
      select jsonb_agg(to_jsonb(company_rows) order by inquiries desc, company_name)
      from company_rows
    ), '[]'::jsonb),
    'instructor_companies', coalesce((
      select jsonb_agg(to_jsonb(instructor_company_rows) order by inquiries desc, instructor_name, company_name)
      from instructor_company_rows
    ), '[]'::jsonb),
    'series', coalesce((
      select jsonb_agg(to_jsonb(series_rows) order by period_start)
      from series_rows
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on public.marketplace_admins from anon, authenticated;
revoke all on public.marketplace_admin_events from anon, authenticated;
revoke all on public.inquiry_followup_responses from anon, authenticated;
grant select on public.marketplace_admins to authenticated;
grant select on public.marketplace_admin_events to authenticated;
grant select on public.inquiry_followup_responses to authenticated;

revoke execute on function public.current_marketplace_admin_status() from public, anon;
revoke execute on function public.current_marketplace_owner_status() from public, anon;
revoke execute on function public.list_marketplace_admins() from public, anon;
revoke execute on function public.grant_marketplace_admin(text) from public, anon;
revoke execute on function public.revoke_marketplace_admin(uuid) from public, anon;
revoke execute on function public.submit_instructor_inquiry_feedback(uuid, text, text, text, date) from public, anon;
revoke execute on function public.get_marketplace_admin_analytics(timestamptz, timestamptz, text, text) from public, anon;
grant execute on function public.current_marketplace_admin_status() to authenticated;
grant execute on function public.current_marketplace_owner_status() to authenticated;
grant execute on function public.list_marketplace_admins() to authenticated;
grant execute on function public.grant_marketplace_admin(text) to authenticated;
grant execute on function public.revoke_marketplace_admin(uuid) to authenticated;
grant execute on function public.submit_instructor_inquiry_feedback(uuid, text, text, text, date) to authenticated;
grant execute on function public.get_marketplace_admin_analytics(timestamptz, timestamptz, text, text) to authenticated;

revoke execute on function public.enqueue_due_inquiry_followups() from public, anon, authenticated;
revoke execute on function public.claim_inquiry_notification_jobs_v2(integer, interval) from public, anon, authenticated;
grant execute on function public.enqueue_due_inquiry_followups() to service_role;
grant execute on function public.claim_inquiry_notification_jobs_v2(integer, interval) to service_role;
