-- Durable instructor approval emails and failed-renewal recovery.
-- Established paying instructors receive a 14-day profile grace period.
-- Instructors without a positive paid invoice are paused immediately.

create table if not exists public.instructor_billing_recoveries (
  id uuid primary key default gen_random_uuid(),
  instructor_profile_id uuid not null
    references public.instructor_profiles(id) on delete cascade,
  stripe_customer_id text not null,
  stripe_subscription_id text not null,
  initial_stripe_invoice_id text not null unique,
  latest_stripe_invoice_id text not null,
  status text not null,
  has_prior_successful_payment boolean not null,
  first_failed_at timestamptz not null,
  last_failed_at timestamptz not null,
  grace_ends_at timestamptz,
  access_paused_at timestamptz,
  recovered_at timestamptz,
  closed_at timestamptz,
  failure_count integer not null default 1,
  last_stripe_event_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instructor_billing_recovery_customer_check check (
    stripe_customer_id ~ '^cus_[A-Za-z0-9]+$'
  ),
  constraint instructor_billing_recovery_subscription_check check (
    stripe_subscription_id ~ '^sub_[A-Za-z0-9]+$'
  ),
  constraint instructor_billing_recovery_initial_invoice_check check (
    initial_stripe_invoice_id ~ '^in_[A-Za-z0-9]+$'
  ),
  constraint instructor_billing_recovery_latest_invoice_check check (
    latest_stripe_invoice_id ~ '^in_[A-Za-z0-9]+$'
  ),
  constraint instructor_billing_recovery_status_check check (
    status in ('grace_period', 'access_paused', 'recovered', 'closed')
  ),
  constraint instructor_billing_recovery_failure_count_check check (
    failure_count > 0
  ),
  constraint instructor_billing_recovery_grace_check check (
    (
      has_prior_successful_payment
      and grace_ends_at is not null
      and grace_ends_at > first_failed_at
    )
    or (
      not has_prior_successful_payment
      and grace_ends_at is null
    )
  )
);

create unique index if not exists instructor_billing_recovery_one_open
  on public.instructor_billing_recoveries (instructor_profile_id)
  where status in ('grace_period', 'access_paused');

create index if not exists instructor_billing_recovery_expiry_idx
  on public.instructor_billing_recoveries (grace_ends_at, id)
  where status = 'grace_period';

alter table public.membership_admin_events
  drop constraint if exists membership_admin_events_type_check;

alter table public.membership_admin_events
  add constraint membership_admin_events_type_check check (
    event_type in (
      'founding_assigned', 'guarantee_updated', 'guarantee_fulfilled',
      'claim_received', 'claim_reviewed', 'refund_verified', 'benefits_ended',
      'offer_redeemed', 'paid_invoice_recorded', 'guarantee_started',
      'billing_grace_started', 'first_payment_failed', 'billing_recovered',
      'billing_recovery_closed', 'billing_grace_expired'
    )
  );

create table if not exists public.instructor_service_notification_jobs (
  id bigint generated by default as identity primary key,
  instructor_profile_id uuid not null
    references public.instructor_profiles(id) on delete cascade,
  billing_recovery_id uuid
    references public.instructor_billing_recoveries(id) on delete cascade,
  notification_type text not null,
  dedupe_key text not null,
  delivered_to_email text not null,
  login_email text not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  provider_message_id text,
  last_error text,
  sent_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint instructor_service_notification_type_check check (
    notification_type in (
      'profile_approved',
      'activation_payment_failed',
      'billing_grace_started',
      'billing_access_paused'
    )
  ),
  constraint instructor_service_notification_recovery_check check (
    (
      notification_type in ('profile_approved', 'activation_payment_failed')
      and billing_recovery_id is null
    )
    or (
      notification_type in ('billing_grace_started', 'billing_access_paused')
      and billing_recovery_id is not null
    )
  ),
  constraint instructor_service_notification_dedupe_check check (
    nullif(trim(dedupe_key), '') is not null
  ),
  constraint instructor_service_notification_email_check check (
    delivered_to_email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'
    and login_email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'
  ),
  constraint instructor_service_notification_status_check check (
    status in ('pending', 'processing', 'sent', 'failed', 'canceled')
  ),
  constraint instructor_service_notification_attempts_check check (
    attempts between 0 and 6
  ),
  constraint instructor_service_notification_unique
    unique (notification_type, dedupe_key)
);

create index if not exists instructor_service_notification_pending_idx
  on public.instructor_service_notification_jobs (status, available_at, id)
  where status in ('pending', 'processing');

create or replace function public.enqueue_instructor_profile_approval_email_if_ready(
  p_instructor_profile_id uuid
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  profile public.instructor_profiles;
  recipient_email text;
  activation_ready boolean;
begin
  if p_instructor_profile_id is null then
    return 'invalid_profile';
  end if;

  select profile_record.* into profile
  from public.instructor_profiles profile_record
  where profile_record.id = p_instructor_profile_id;

  if profile.id is null or profile.status <> 'published'
    or profile.approved_at is null or profile.slug is null then
    return 'not_ready';
  end if;

  activation_ready := exists (
    select 1
    from public.instructor_lifetime_access access
    where access.instructor_profile_id = profile.id
  ) or (
    exists (
      select 1
      from public.instructor_memberships membership
      where membership.instructor_profile_id = profile.id
        and membership.status in ('active', 'trialing')
    )
    and not exists (
      select 1
      from public.instructor_offer_entitlements entitlement
      where entitlement.instructor_profile_id = profile.id
        and entitlement.redeemed_at is null
    )
  );

  if not activation_ready then
    return 'not_ready';
  end if;

  select lower(trim(account.email)) into recipient_email
  from public.accounts account
  where account.id = profile.account_id;

  if recipient_email is null
    or recipient_email !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' then
    return 'recipient_missing';
  end if;

  insert into public.instructor_service_notification_jobs (
    instructor_profile_id,
    notification_type,
    dedupe_key,
    delivered_to_email,
    login_email
  ) values (
    profile.id,
    'profile_approved',
    profile.id::text,
    recipient_email,
    recipient_email
  ) on conflict (notification_type, dedupe_key) do nothing;

  if found then
    return 'queued';
  end if;
  return 'duplicate';
end;
$$;

create or replace function public.enqueue_instructor_activation_payment_failure(
  p_instructor_profile_id uuid,
  p_failed_activation_id uuid
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  profile public.instructor_profiles;
  recipient_email text;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service_role_required';
  end if;

  if p_instructor_profile_id is null or p_failed_activation_id is null then
    raise exception 'invalid_activation_failure';
  end if;

  select profile_record.* into profile
  from public.instructor_profiles profile_record
  where profile_record.id = p_instructor_profile_id;

  if profile.id is null or profile.status <> 'draft' then
    return 'not_ready';
  end if;

  select lower(trim(account.email)) into recipient_email
  from public.accounts account
  where account.id = profile.account_id;

  if recipient_email is null
    or recipient_email !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' then
    return 'recipient_missing';
  end if;

  insert into public.instructor_service_notification_jobs (
    instructor_profile_id,
    notification_type,
    dedupe_key,
    delivered_to_email,
    login_email
  ) values (
    profile.id,
    'activation_payment_failed',
    p_failed_activation_id::text,
    recipient_email,
    recipient_email
  ) on conflict (notification_type, dedupe_key) do nothing;

  if found then
    return 'queued';
  end if;
  return 'duplicate';
end;
$$;

create or replace function public.enqueue_approval_email_from_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.enqueue_instructor_profile_approval_email_if_ready(new.id);
  return new;
end;
$$;

create or replace function public.enqueue_approval_email_from_membership()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.enqueue_instructor_profile_approval_email_if_ready(
    new.instructor_profile_id
  );
  return new;
end;
$$;

create or replace function public.enqueue_approval_email_from_entitlement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.enqueue_instructor_profile_approval_email_if_ready(
    new.instructor_profile_id
  );
  return new;
end;
$$;

drop trigger if exists enqueue_instructor_profile_approval_email
  on public.instructor_profiles;
create trigger enqueue_instructor_profile_approval_email
  after insert or update of status on public.instructor_profiles
  for each row
  when (new.status = 'published')
  execute function public.enqueue_approval_email_from_profile();

drop trigger if exists enqueue_instructor_membership_approval_email
  on public.instructor_memberships;
create trigger enqueue_instructor_membership_approval_email
  after insert or update of status on public.instructor_memberships
  for each row
  when (new.status in ('active', 'trialing'))
  execute function public.enqueue_approval_email_from_membership();

drop trigger if exists enqueue_instructor_entitlement_approval_email
  on public.instructor_offer_entitlements;
create trigger enqueue_instructor_entitlement_approval_email
  after insert or update of redeemed_at on public.instructor_offer_entitlements
  for each row
  when (new.redeemed_at is not null)
  execute function public.enqueue_approval_email_from_entitlement();

create or replace function public.preserve_profile_during_billing_grace()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status = 'published' and new.status = 'approved' and exists (
    select 1
    from public.instructor_billing_recoveries recovery
    where recovery.instructor_profile_id = old.id
      and recovery.status = 'grace_period'
      and recovery.grace_ends_at > now()
  ) then
    new.status := 'published';
    new.published_at := old.published_at;
  end if;
  return new;
end;
$$;

drop trigger if exists preserve_profile_during_billing_grace
  on public.instructor_profiles;
create trigger preserve_profile_during_billing_grace
  before update of status on public.instructor_profiles
  for each row execute function public.preserve_profile_during_billing_grace();

create or replace function public.begin_instructor_billing_recovery(
  p_event_id text,
  p_instructor_profile_id uuid,
  p_stripe_customer_id text,
  p_stripe_subscription_id text,
  p_stripe_invoice_id text,
  p_failed_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  recovery public.instructor_billing_recoveries;
  has_paid boolean;
  recipient_email text;
  next_status text;
  next_grace_ends_at timestamptz;
  notification_type text;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required';
  end if;
  if nullif(trim(p_event_id), '') is null
    or p_instructor_profile_id is null
    or p_stripe_customer_id is null
    or p_stripe_customer_id !~ '^cus_[A-Za-z0-9]+$'
    or p_stripe_subscription_id is null
    or p_stripe_subscription_id !~ '^sub_[A-Za-z0-9]+$'
    or p_stripe_invoice_id is null
    or p_stripe_invoice_id !~ '^in_[A-Za-z0-9]+$'
    or p_failed_at is null then
    raise exception 'Billing recovery facts are invalid';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_instructor_profile_id::text, 0)
  );

  if exists (
    select 1
    from public.instructor_lifetime_access access
    where access.instructor_profile_id = p_instructor_profile_id
  ) then
    return jsonb_build_object('result', 'lifetime_access_ignored');
  end if;

  if not exists (
    select 1
    from public.instructor_memberships membership
    where membership.instructor_profile_id = p_instructor_profile_id
      and membership.stripe_customer_id = p_stripe_customer_id
      and membership.stripe_subscription_id = p_stripe_subscription_id
  ) then
    raise exception 'Billing recovery does not match the instructor membership';
  end if;

  select recovery_record.* into recovery
  from public.instructor_billing_recoveries recovery_record
  where recovery_record.initial_stripe_invoice_id = p_stripe_invoice_id
     or (
       recovery_record.instructor_profile_id = p_instructor_profile_id
       and recovery_record.status in ('grace_period', 'access_paused')
     )
  order by
    (recovery_record.initial_stripe_invoice_id = p_stripe_invoice_id) desc,
    recovery_record.created_at desc
  limit 1
  for update;

  if recovery.id is not null then
    if recovery.stripe_customer_id is distinct from p_stripe_customer_id
      or recovery.stripe_subscription_id is distinct from
        p_stripe_subscription_id then
      raise exception 'Billing recovery was recorded with different Stripe facts';
    end if;

    if recovery.status not in ('grace_period', 'access_paused') then
      return jsonb_build_object(
        'result', 'closed_event_ignored',
        'recoveryId', recovery.id,
        'status', recovery.status
      );
    end if;

    if recovery.last_stripe_event_id = trim(p_event_id) then
      return jsonb_build_object(
        'result', 'duplicate',
        'recoveryId', recovery.id,
        'status', recovery.status,
        'graceEndsAt', recovery.grace_ends_at,
        'hasPriorSuccessfulPayment', recovery.has_prior_successful_payment
      );
    end if;

    update public.instructor_billing_recoveries
    set latest_stripe_invoice_id = p_stripe_invoice_id,
        last_failed_at = greatest(last_failed_at, p_failed_at),
        failure_count = failure_count + 1,
        last_stripe_event_id = trim(p_event_id),
        updated_at = now()
    where id = recovery.id
    returning * into recovery;

    return jsonb_build_object(
      'result', 'existing',
      'recoveryId', recovery.id,
      'status', recovery.status,
      'graceEndsAt', recovery.grace_ends_at,
      'hasPriorSuccessfulPayment', recovery.has_prior_successful_payment
    );
  end if;

  select exists (
    select 1
    from public.membership_paid_invoices invoice
    where invoice.instructor_profile_id = p_instructor_profile_id
  ) into has_paid;

  next_status := case when has_paid then 'grace_period' else 'access_paused' end;
  next_grace_ends_at := case
    when has_paid then p_failed_at + interval '14 days'
    else null
  end;

  insert into public.instructor_billing_recoveries (
    instructor_profile_id,
    stripe_customer_id,
    stripe_subscription_id,
    initial_stripe_invoice_id,
    latest_stripe_invoice_id,
    status,
    has_prior_successful_payment,
    first_failed_at,
    last_failed_at,
    grace_ends_at,
    access_paused_at,
    last_stripe_event_id
  ) values (
    p_instructor_profile_id,
    p_stripe_customer_id,
    p_stripe_subscription_id,
    p_stripe_invoice_id,
    p_stripe_invoice_id,
    next_status,
    has_paid,
    p_failed_at,
    p_failed_at,
    next_grace_ends_at,
    case when has_paid then null else p_failed_at end,
    trim(p_event_id)
  ) returning * into recovery;

  if has_paid then
    update public.instructor_profiles
    set status = 'published',
        published_at = coalesce(published_at, now()),
        updated_at = now()
    where id = p_instructor_profile_id
      and approved_at is not null
      and status = 'approved';
    notification_type := 'billing_grace_started';
  else
    update public.instructor_profiles
    set status = 'approved',
        updated_at = now()
    where id = p_instructor_profile_id
      and status = 'published';
    notification_type := 'billing_access_paused';
  end if;

  insert into public.membership_admin_events (
    instructor_profile_id,
    event_type,
    detail
  ) values (
    p_instructor_profile_id,
    case when has_paid
      then 'billing_grace_started'
      else 'first_payment_failed'
    end,
    jsonb_build_object(
      'recovery_id', recovery.id,
      'stripe_invoice_id', p_stripe_invoice_id,
      'grace_ends_at', next_grace_ends_at,
      'has_prior_successful_payment', has_paid
    )
  );

  select lower(trim(account.email)) into recipient_email
  from public.instructor_profiles profile
  join public.accounts account on account.id = profile.account_id
  where profile.id = p_instructor_profile_id;

  if recipient_email is not null
    and recipient_email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' then
    insert into public.instructor_service_notification_jobs (
      instructor_profile_id,
      billing_recovery_id,
      notification_type,
      dedupe_key,
      delivered_to_email,
      login_email
    ) values (
      p_instructor_profile_id,
      recovery.id,
      notification_type,
      recovery.id::text,
      recipient_email,
      recipient_email
    ) on conflict (notification_type, dedupe_key) do nothing;
  end if;

  return jsonb_build_object(
    'result', 'created',
    'recoveryId', recovery.id,
    'status', recovery.status,
    'graceEndsAt', recovery.grace_ends_at,
    'hasPriorSuccessfulPayment', recovery.has_prior_successful_payment
  );
end;
$$;

create or replace function public.resolve_instructor_billing_recovery(
  p_instructor_profile_id uuid,
  p_stripe_subscription_id text,
  p_stripe_invoice_id text,
  p_recovered_at timestamptz
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  recovery_id uuid;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required';
  end if;
  if p_instructor_profile_id is null
    or p_stripe_subscription_id is null
    or p_stripe_subscription_id !~ '^sub_[A-Za-z0-9]+$'
    or p_stripe_invoice_id is null
    or p_stripe_invoice_id !~ '^in_[A-Za-z0-9]+$'
    or p_recovered_at is null then
    raise exception 'Billing recovery resolution facts are invalid';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_instructor_profile_id::text, 0)
  );

  if not exists (
    select 1
    from public.membership_paid_invoices invoice
    where invoice.instructor_profile_id = p_instructor_profile_id
      and invoice.stripe_subscription_id = p_stripe_subscription_id
      and invoice.stripe_invoice_id = p_stripe_invoice_id
  ) then
    return 'paid_invoice_not_recorded';
  end if;

  select recovery.id into recovery_id
  from public.instructor_billing_recoveries recovery
  where recovery.instructor_profile_id = p_instructor_profile_id
    and recovery.stripe_subscription_id = p_stripe_subscription_id
    and recovery.status in ('grace_period', 'access_paused')
    and p_stripe_invoice_id in (
      recovery.initial_stripe_invoice_id,
      recovery.latest_stripe_invoice_id
    )
  limit 1
  for update;

  if recovery_id is null then
    return 'no_open_recovery';
  end if;

  update public.instructor_billing_recoveries
  set status = 'recovered',
      recovered_at = p_recovered_at,
      updated_at = now()
  where id = recovery_id;

  update public.instructor_profiles profile
  set status = 'published',
      published_at = coalesce(profile.published_at, now()),
      updated_at = now()
  where profile.id = p_instructor_profile_id
    and profile.approved_at is not null
    and profile.status = 'approved'
    and exists (
      select 1
      from public.instructor_memberships membership
      where membership.instructor_profile_id = profile.id
        and membership.stripe_subscription_id = p_stripe_subscription_id
        and membership.status in ('active', 'trialing')
    );

  insert into public.membership_admin_events (
    instructor_profile_id,
    event_type,
    detail
  ) values (
    p_instructor_profile_id,
    'billing_recovered',
    jsonb_build_object(
      'recovery_id', recovery_id,
      'stripe_invoice_id', p_stripe_invoice_id
    )
  );

  return 'recovered';
end;
$$;

create or replace function public.close_instructor_billing_recovery(
  p_instructor_profile_id uuid,
  p_stripe_subscription_id text,
  p_reason text,
  p_closed_at timestamptz
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_count integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required';
  end if;
  if p_instructor_profile_id is null
    or p_stripe_subscription_id is null
    or p_stripe_subscription_id !~ '^sub_[A-Za-z0-9]+$'
    or nullif(trim(p_reason), '') is null
    or p_closed_at is null then
    raise exception 'Billing recovery closure facts are invalid';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_instructor_profile_id::text, 0)
  );

  update public.instructor_billing_recoveries
  set status = 'closed',
      closed_at = p_closed_at,
      updated_at = now()
  where instructor_profile_id = p_instructor_profile_id
    and stripe_subscription_id = p_stripe_subscription_id
    and status in ('grace_period', 'access_paused');

  get diagnostics updated_count = row_count;
  if updated_count = 0 then
    return 'no_open_recovery';
  end if;

  update public.instructor_profiles
  set status = 'approved',
      updated_at = now()
  where id = p_instructor_profile_id
    and status = 'published';

  insert into public.membership_admin_events (
    instructor_profile_id,
    event_type,
    detail
  ) values (
    p_instructor_profile_id,
    'billing_recovery_closed',
    jsonb_build_object('reason', trim(p_reason))
  );

  return 'closed';
end;
$$;

create or replace function public.expire_instructor_billing_grace_periods()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  recovery public.instructor_billing_recoveries;
  expired_count integer := 0;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required';
  end if;

  for recovery in
    select recovery_record.*
    from public.instructor_billing_recoveries recovery_record
    where recovery_record.status = 'grace_period'
      and recovery_record.grace_ends_at <= now()
    order by recovery_record.grace_ends_at, recovery_record.id
    for update skip locked
  loop
    perform pg_advisory_xact_lock(
      hashtextextended(recovery.instructor_profile_id::text, 0)
    );

    update public.instructor_billing_recoveries
    set status = 'access_paused',
        access_paused_at = now(),
        updated_at = now()
    where id = recovery.id
      and status = 'grace_period';

    if found then
      update public.instructor_profiles
      set status = 'approved',
          updated_at = now()
      where id = recovery.instructor_profile_id
        and status = 'published';

      insert into public.membership_admin_events (
        instructor_profile_id,
        event_type,
        detail
      ) values (
        recovery.instructor_profile_id,
        'billing_grace_expired',
        jsonb_build_object(
          'recovery_id', recovery.id,
          'grace_ended_at', recovery.grace_ends_at
        )
      );

      expired_count := expired_count + 1;
    end if;
  end loop;

  return expired_count;
end;
$$;

create or replace function public.claim_instructor_service_notification_jobs(
  p_limit integer default 10,
  p_lock_timeout interval default interval '10 minutes'
)
returns table (
  job_id bigint,
  attempt_number integer,
  notification_type text,
  instructor_profile_id uuid,
  billing_recovery_id uuid,
  delivered_to_email text,
  login_email text,
  display_name text,
  profile_slug text,
  recovery_status text,
  has_prior_successful_payment boolean,
  first_failed_at timestamptz,
  grace_ends_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  with suppressed as (
    update public.instructor_service_notification_jobs job
    set status = 'canceled',
        completed_at = now(),
        locked_at = null,
        last_error = 'Billing issue was resolved before the email was sent'
    where job.status in ('pending', 'processing')
      and job.billing_recovery_id is not null
      and exists (
        select 1
        from public.instructor_billing_recoveries recovery
        where recovery.id = job.billing_recovery_id
          and recovery.status in ('recovered', 'closed')
      )
    returning job.id
  ), exhausted as (
    update public.instructor_service_notification_jobs job
    set status = 'failed',
        completed_at = now(),
        locked_at = null,
        last_error = coalesce(
          job.last_error,
          'Worker stopped before the final attempt completed'
        )
    where job.status = 'processing'
      and job.attempts >= 6
      and coalesce(job.locked_at, '-infinity'::timestamptz)
        < now() - greatest(p_lock_timeout, interval '1 minute')
    returning job.id
  ), candidates as (
    select job.id
    from public.instructor_service_notification_jobs job
    where job.attempts < 6
      and (
        (job.status = 'pending' and job.available_at <= now())
        or (
          job.status = 'processing'
          and coalesce(job.locked_at, '-infinity'::timestamptz)
            < now() - greatest(p_lock_timeout, interval '1 minute')
        )
      )
    order by job.available_at, job.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 10), 25))
  ), claimed as (
    update public.instructor_service_notification_jobs job
    set status = 'processing',
        attempts = job.attempts + 1,
        locked_at = now(),
        last_error = null
    from candidates
    where job.id = candidates.id
    returning job.*
  )
  select
    claimed.id,
    claimed.attempts,
    claimed.notification_type,
    claimed.instructor_profile_id,
    claimed.billing_recovery_id,
    claimed.delivered_to_email,
    claimed.login_email,
    profile.display_name,
    profile.slug,
    recovery.status,
    recovery.has_prior_successful_payment,
    recovery.first_failed_at,
    recovery.grace_ends_at
  from claimed
  join public.instructor_profiles profile
    on profile.id = claimed.instructor_profile_id
  left join public.instructor_billing_recoveries recovery
    on recovery.id = claimed.billing_recovery_id;
$$;

create or replace function public.complete_instructor_service_notification_job(
  p_job_id bigint,
  p_success boolean,
  p_provider_message_id text default null,
  p_error text default null,
  p_retryable boolean default false
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.instructor_service_notification_jobs;
  retry_seconds integer;
begin
  select * into job
  from public.instructor_service_notification_jobs
  where id = p_job_id
  for update;

  if job.id is null then
    raise exception 'Instructor service notification job not found';
  end if;
  if job.status = 'sent' then
    return 'sent';
  end if;
  if job.status <> 'processing' then
    raise exception 'Instructor service notification job is not processing';
  end if;

  if p_success then
    update public.instructor_service_notification_jobs
    set status = 'sent',
        provider_message_id = nullif(trim(p_provider_message_id), ''),
        sent_at = now(),
        completed_at = now(),
        locked_at = null,
        last_error = null
    where id = job.id;
    return 'sent';
  end if;

  if p_retryable and job.attempts < 6 then
    retry_seconds := least(
      1800,
      (30 * power(2, greatest(job.attempts - 1, 0)))::integer
    );
    update public.instructor_service_notification_jobs
    set status = 'pending',
        available_at = now() + retry_seconds * interval '1 second',
        locked_at = null,
        last_error = left(coalesce(p_error, 'Provider request failed'), 2000)
    where id = job.id;
    return 'pending';
  end if;

  update public.instructor_service_notification_jobs
  set status = 'failed',
      completed_at = now(),
      locked_at = null,
      last_error = left(coalesce(p_error, 'Provider request failed'), 2000)
  where id = job.id;
  return 'failed';
end;
$$;

create or replace function public.defer_instructor_service_notification_job(
  p_job_id bigint,
  p_error text,
  p_delay interval default interval '15 minutes'
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.instructor_service_notification_jobs;
begin
  select * into job
  from public.instructor_service_notification_jobs
  where id = p_job_id
  for update;

  if job.id is null then
    raise exception 'Instructor service notification job not found';
  end if;
  if job.status = 'sent' then
    return 'sent';
  end if;
  if job.status <> 'processing' then
    raise exception 'Instructor service notification job is not processing';
  end if;

  update public.instructor_service_notification_jobs
  set status = 'pending',
      attempts = greatest(attempts - 1, 0),
      available_at = now() + greatest(p_delay, interval '1 minute'),
      locked_at = null,
      last_error = left(
        coalesce(p_error, 'Notification provider is not configured'),
        2000
      )
  where id = job.id;

  return 'pending';
end;
$$;

alter table public.instructor_billing_recoveries enable row level security;
alter table public.instructor_service_notification_jobs enable row level security;

drop policy if exists "instructors and admins read billing recoveries"
  on public.instructor_billing_recoveries;
create policy "instructors and admins read billing recoveries"
  on public.instructor_billing_recoveries
  for select to authenticated using (
    exists (
      select 1
      from public.instructor_profiles profile
      where profile.id = instructor_profile_id
        and profile.account_id = auth.uid()
    )
    or public.is_marketplace_admin()
  );

drop policy if exists "admins read instructor service notifications"
  on public.instructor_service_notification_jobs;
create policy "admins read instructor service notifications"
  on public.instructor_service_notification_jobs
  for select to authenticated using (public.is_marketplace_admin());

revoke all on public.instructor_billing_recoveries from anon, authenticated;
revoke all on public.instructor_service_notification_jobs from anon, authenticated;
grant select on public.instructor_billing_recoveries to authenticated;
grant select on public.instructor_service_notification_jobs to authenticated;

revoke execute on function public.enqueue_instructor_profile_approval_email_if_ready(uuid)
  from public, anon, authenticated;
revoke execute on function public.enqueue_approval_email_from_profile()
  from public, anon, authenticated;
revoke execute on function public.enqueue_approval_email_from_membership()
  from public, anon, authenticated;
revoke execute on function public.enqueue_approval_email_from_entitlement()
  from public, anon, authenticated;
revoke execute on function public.preserve_profile_during_billing_grace()
  from public, anon, authenticated;
revoke execute on function public.enqueue_instructor_activation_payment_failure(uuid, uuid)
  from public, anon, authenticated;
revoke execute on function public.begin_instructor_billing_recovery(text, uuid, text, text, text, timestamptz)
  from public, anon, authenticated;
revoke execute on function public.resolve_instructor_billing_recovery(uuid, text, text, timestamptz)
  from public, anon, authenticated;
revoke execute on function public.close_instructor_billing_recovery(uuid, text, text, timestamptz)
  from public, anon, authenticated;
revoke execute on function public.expire_instructor_billing_grace_periods()
  from public, anon, authenticated;
revoke execute on function public.claim_instructor_service_notification_jobs(integer, interval)
  from public, anon, authenticated;
revoke execute on function public.complete_instructor_service_notification_job(bigint, boolean, text, text, boolean)
  from public, anon, authenticated;
revoke execute on function public.defer_instructor_service_notification_job(bigint, text, interval)
  from public, anon, authenticated;

grant execute on function public.begin_instructor_billing_recovery(text, uuid, text, text, text, timestamptz)
  to service_role;
grant execute on function public.enqueue_instructor_activation_payment_failure(uuid, uuid)
  to service_role;
grant execute on function public.resolve_instructor_billing_recovery(uuid, text, text, timestamptz)
  to service_role;
grant execute on function public.close_instructor_billing_recovery(uuid, text, text, timestamptz)
  to service_role;
grant execute on function public.expire_instructor_billing_grace_periods()
  to service_role;
grant execute on function public.claim_instructor_service_notification_jobs(integer, interval)
  to service_role;
grant execute on function public.complete_instructor_service_notification_job(bigint, boolean, text, text, boolean)
  to service_role;
grant execute on function public.defer_instructor_service_notification_job(bigint, text, interval)
  to service_role;
