-- Durable administrator email alerts for instructor profile submissions.
-- The existing notification worker delivers these jobs once per minute.

create table if not exists public.profile_submission_notification_jobs (
  id bigint generated by default as identity primary key,
  instructor_profile_id uuid not null
    references public.instructor_profiles(id) on delete cascade,
  submission_sequence integer not null,
  delivered_to_email text not null,
  login_email text not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  provider_message_id text,
  last_error text,
  submitted_at timestamptz not null default now(),
  sent_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint profile_submission_notification_sequence_check
    check (submission_sequence > 0),
  constraint profile_submission_notification_email_check check (
    delivered_to_email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'
    and login_email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'
  ),
  constraint profile_submission_notification_status_check check (
    status in ('pending', 'processing', 'sent', 'failed')
  ),
  constraint profile_submission_notification_attempts_check
    check (attempts between 0 and 6),
  constraint profile_submission_notification_unique
    unique (instructor_profile_id, submission_sequence)
);

create index if not exists profile_submission_notification_pending_idx
  on public.profile_submission_notification_jobs (status, available_at, id)
  where status in ('pending', 'processing');

alter table public.profile_submission_notification_jobs enable row level security;

drop policy if exists "admins read profile submission notifications"
  on public.profile_submission_notification_jobs;
create policy "admins read profile submission notifications"
  on public.profile_submission_notification_jobs
  for select to authenticated using (public.is_marketplace_admin());

create or replace function public.enqueue_profile_submission_admin_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  next_sequence integer;
begin
  if new.status <> 'pending_review'
    or (tg_op = 'UPDATE' and old.status = 'pending_review') then
    return new;
  end if;

  select coalesce(max(job.submission_sequence), 0) + 1
  into next_sequence
  from public.profile_submission_notification_jobs job
  where job.instructor_profile_id = new.id;

  insert into public.profile_submission_notification_jobs (
    instructor_profile_id,
    submission_sequence,
    delivered_to_email,
    login_email,
    submitted_at
  ) values (
    new.id,
    next_sequence,
    'cjwheelock1@gmail.com',
    'cj.wheelock1@gmail.com',
    now()
  )
  on conflict (instructor_profile_id, submission_sequence) do nothing;

  return new;
end;
$$;

drop trigger if exists enqueue_profile_submission_admin_notification
  on public.instructor_profiles;
create trigger enqueue_profile_submission_admin_notification
  after insert or update of status on public.instructor_profiles
  for each row execute function public.enqueue_profile_submission_admin_notification();

-- Alert the administrator about profiles that are already waiting when this
-- migration is applied. Future submissions and resubmissions use the trigger.
insert into public.profile_submission_notification_jobs (
  instructor_profile_id,
  submission_sequence,
  delivered_to_email,
  login_email,
  submitted_at
)
select
  profile.id,
  1,
  'cjwheelock1@gmail.com',
  'cj.wheelock1@gmail.com',
  profile.updated_at
from public.instructor_profiles profile
where profile.status = 'pending_review'
on conflict (instructor_profile_id, submission_sequence) do nothing;

create or replace function public.claim_profile_submission_notification_jobs(
  p_limit integer default 10,
  p_lock_timeout interval default interval '10 minutes'
)
returns table (
  job_id bigint,
  attempt_number integer,
  instructor_profile_id uuid,
  delivered_to_email text,
  login_email text,
  display_name text,
  business_name text,
  city text,
  region text,
  submitted_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  with exhausted as (
    update public.profile_submission_notification_jobs job
    set status = 'failed',
        completed_at = now(),
        locked_at = null,
        last_error = coalesce(
          job.last_error,
          'Worker stopped before the final attempt completed'
        )
    where job.status = 'processing'
      and job.attempts >= 6
      and coalesce(job.locked_at, '-infinity'::timestamptz)
        < now() - greatest(p_lock_timeout, interval '1 minute')
    returning job.id
  ), candidates as (
    select job.id
    from public.profile_submission_notification_jobs job
    where job.attempts < 6
      and (
        (job.status = 'pending' and job.available_at <= now())
        or (
          job.status = 'processing'
          and coalesce(job.locked_at, '-infinity'::timestamptz)
            < now() - greatest(p_lock_timeout, interval '1 minute')
        )
      )
    order by job.available_at, job.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 10), 25))
  ), claimed as (
    update public.profile_submission_notification_jobs job
    set status = 'processing',
        attempts = job.attempts + 1,
        locked_at = now(),
        last_error = null
    from candidates
    where job.id = candidates.id
    returning job.*
  )
  select
    claimed.id,
    claimed.attempts,
    claimed.instructor_profile_id,
    claimed.delivered_to_email,
    claimed.login_email,
    profile.display_name,
    profile.business_name,
    profile.city,
    profile.region,
    claimed.submitted_at
  from claimed
  join public.instructor_profiles profile
    on profile.id = claimed.instructor_profile_id;
$$;

create or replace function public.complete_profile_submission_notification_job(
  p_job_id bigint,
  p_success boolean,
  p_provider_message_id text default null,
  p_error text default null,
  p_retryable boolean default false
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.profile_submission_notification_jobs;
  next_status text;
  retry_seconds integer;
begin
  select * into job
  from public.profile_submission_notification_jobs
  where id = p_job_id
  for update;

  if job.id is null then
    raise exception 'Profile submission notification job not found';
  end if;
  if job.status = 'sent' then
    return 'sent';
  end if;
  if job.status <> 'processing' then
    raise exception 'Profile submission notification job is not processing';
  end if;

  if p_success then
    next_status := 'sent';
    update public.profile_submission_notification_jobs
    set status = 'sent',
        provider_message_id = nullif(trim(p_provider_message_id), ''),
        sent_at = now(),
        completed_at = now(),
        locked_at = null,
        last_error = null
    where id = job.id;
  elsif p_retryable and job.attempts < 6 then
    next_status := 'pending';
    retry_seconds := least(
      1800,
      (30 * power(2, greatest(job.attempts - 1, 0)))::integer
    );
    update public.profile_submission_notification_jobs
    set status = 'pending',
        available_at = now() + retry_seconds * interval '1 second',
        locked_at = null,
        last_error = left(coalesce(p_error, 'Provider request failed'), 2000)
    where id = job.id;
  else
    next_status := 'failed';
    update public.profile_submission_notification_jobs
    set status = 'failed',
        completed_at = now(),
        locked_at = null,
        last_error = left(coalesce(p_error, 'Provider request failed'), 2000)
    where id = job.id;
  end if;

  return next_status;
end;
$$;

create or replace function public.defer_profile_submission_notification_job(
  p_job_id bigint,
  p_error text,
  p_delay interval default interval '15 minutes'
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.profile_submission_notification_jobs;
begin
  select * into job
  from public.profile_submission_notification_jobs
  where id = p_job_id
  for update;

  if job.id is null then
    raise exception 'Profile submission notification job not found';
  end if;
  if job.status = 'sent' then
    return 'sent';
  end if;
  if job.status <> 'processing' then
    raise exception 'Profile submission notification job is not processing';
  end if;

  update public.profile_submission_notification_jobs
  set status = 'pending',
      attempts = greatest(attempts - 1, 0),
      available_at = now() + greatest(p_delay, interval '1 minute'),
      locked_at = null,
      last_error = left(
        coalesce(p_error, 'Notification provider is not configured'),
        2000
      )
  where id = job.id;

  return 'pending';
end;
$$;

revoke all on public.profile_submission_notification_jobs from anon, authenticated;
grant select on public.profile_submission_notification_jobs to authenticated;

revoke execute on function public.enqueue_profile_submission_admin_notification()
  from public, anon, authenticated;
revoke execute on function public.claim_profile_submission_notification_jobs(integer, interval)
  from public, anon, authenticated;
revoke execute on function public.complete_profile_submission_notification_job(bigint, boolean, text, text, boolean)
  from public, anon, authenticated;
revoke execute on function public.defer_profile_submission_notification_job(bigint, text, interval)
  from public, anon, authenticated;

grant execute on function public.claim_profile_submission_notification_jobs(integer, interval)
  to service_role;
grant execute on function public.complete_profile_submission_notification_job(bigint, boolean, text, text, boolean)
  to service_role;
grant execute on function public.defer_profile_submission_notification_job(bigint, text, interval)
  to service_role;
